version: '3'

services:
  web:
    restart: always
    image: muhammadatef/project-nginx:latest
    build:
      context: ./nginx
      dockerfile: ./nginx/Dockerfile
    expose:
      - "8000"
    env_file:
      - ./.env
    environment:
      - REDIS_HOST=redis
    volumes:
      - ./web/static:/pro/web/static
   
    
  nginx:
    restart: always
    image: muhammadatef/project-web:latest
    build:
      context: ./web
      dockerfile: ./web/Dockerfile
    ports:
      - "10080:80"
    volumes:
      - ./web/static:/static
    
  
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    

