version: '3'

services:
  web:
    restart: always
    build: ./web
    expose:
      - "8000"
    env_file:
      - ./.env
    environment:
      - REDIS_HOST=redis
   
    
  nginx:
    restart: always
    build: ./nginx
    ports:
      - "10080:80"
    
  
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    

